remote_theme: niklasbuschmann/contrast@v2.11
plugins:
 - jekyll-feed
 - jekyll-remote-theme


title: "Byte Sized Blog"
description: >
  Welcome to my blog page! I am a graduate student studying nuclear/particle
  physics, and you'll find here various tutorials, code snippets, and whatever else has
  helped me along my way to a PhD. I hope you find something useful!
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:scheuer.ks@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/kevScheuer"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/kevin-scheuer/"}

include:
  - assets/css/custom.css
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/
